default: &default
  adapter: sqlite3
  pool: 5
  timeout: 5000

development:
#  <<: *default
  adapter:  <%= ENV["development.database.adapter"] %>
  encoding: <%= ENV["development.database.encoding"] %>
  database: <%= ENV["development.database.database"] %>
  username: <%= ENV["development.database.username"] %>
  password: <%= ENV["development.database.password"] %>
  host:     <%= ENV["development.database.host"] %>
  port:     <%= ENV["development.database.port"] %>  
  

test:
  adapter:  <%= ENV["test.database.adapter"] %>
  encoding: <%= ENV["test.database.encoding"] %>
  database: <%= ENV["test.database.database"] %>
  username: <%= ENV["test.database.username"] %>
  password: <%= ENV["test.database.password"] %>
  host:     <%= ENV["test.database.host"] %>
  port:     <%= ENV["test.database.port"] %>

production:
  adapter:  <%= ENV["production.database.adapter"] %>
  encoding: <%= ENV["production.database.encoding"] %>
  database: <%= ENV["production.database.database"] %>
  username: <%= ENV["production.database.username"] %>
  password: <%= ENV["production.database.password"] %>
  host:     <%= ENV["production.database.host"] %>
  port:     <%= ENV["production.database.port"] %>